# Generated by Django 6.1 on 2026-10-09 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}', 'أدخل رقم الجوال بدون المفتاح ')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(choices=[('store', 'محل'), ('person', 'شخص')], max_length=50)),
                ('name_store', models.CharField(blank=True, help_text='للمحل يجب وضع أسمه', max_length=50, null=True)),
                ('type_phone', models.CharField(help_text='smasung s22 نوع الجهاز باسمه مثل', max_length=50)),
                ('phone_status', models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], help_text='حالة الجهاز', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='المبلغ بالجنيه السوداني', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='Telephone.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=50, verbose_name='المعالج')),
                ('memory', models.CharField(max_length=50, verbose_name='ذاكرة')),
                ('ram', models.CharField(max_length=50, verbose_name='رام')),
                ('battery', models.CharField(max_length=50, verbose_name='البطارية')),
                ('camera', models.CharField(max_length=50, verbose_name='كاميرا')),
                ('phone_specs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='Telephone.phone')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number_IMEI', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'الأرقام الصحيحة تتكون من 15 رقم')])),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('seller_confirmed', models.BooleanField(default=False)),
                ('contract', models.BooleanField(default=True)),
                ('payment_url', models.URLField(blank=True, help_text='طريقة الدفع عن طريق محفظة ألكترونية مثل ماي كاشي', null=True)),
                ('transfer_id', models.CharField(blank=True, help_text='أرقام العملية لتحويلة ', max_length=25, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'في انتظار الدفع'), ('PAID_HELD', 'تم الدفع ومحجوز لدي المنصة'), ('COMPLETED', 'مكتمل وتم التسليم'), ('REFUNDED', 'تم أرجاع المال للمشتري'), ('FAILED', 'فشلت العملية')], max_length=45)),
                ('pdf', models.FileField(blank=True, help_text='PDF الحصول علي ألايصال بصيغة', null=True, upload_to='')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to=settings.AUTH_USER_MODEL)),
                ('phone_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='Telephone.phone')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
