# Generated by Django 6.1 on 2026-10-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telephone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='phone_specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_specs', to='Telephone.phone'),
        ),
    ]
