# Generated by Django 6.1 on 2026-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telephone', '0003_alter_specs_phone_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image_phone',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
